# Generated by Django 2.2.3 on 2019-08-29 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190826_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gradeReceived',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('NP', 'NP'), ('P', 'P'), ('N/A', 'N/A')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='homework',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pop_quizzes',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 9, 10, 25, 65588), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='webcast',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 9, 10, 25, 62945), verbose_name='data published'),
        ),
    ]
