# Generated by Django 2.2.3 on 2019-08-29 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190829_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 9, 13, 43, 704452), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 9, 13, 43, 702764), verbose_name='data published'),
        ),
    ]
