# Generated by Django 2.2.3 on 2019-08-30 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190829_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='InterestingRating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNum',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.SchoolCourse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='easyRating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='gradeReceived',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('NP', 'NP'), ('P', 'P'), ('N/A', 'N/A')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='homework',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='numProjects',
            field=models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='numTests',
            field=models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='pop_quizzes',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_content',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Review Content: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 18, 23, 7, 476042), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Review Title: '),
        ),
        migrations.AlterField(
            model_name='course',
            name='testDiff',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_spent',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '0-2'), ('2', '3-4'), ('3', '5-6'), ('4', '7-8'), ('5', '9-10'), ('6', '10-12'), ('7', '12-14'), ('8', '15-17'), ('9', '18-20'), ('10', '20+')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='webcast',
            field=models.CharField(blank=True, choices=[('', ''), ('True', 'Yes'), ('False', 'No')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='abbrev',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolcourse',
            name='courseNumber',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolcourse',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolcourse',
            name='school',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.School'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 18, 23, 7, 474168), verbose_name='data published'),
        ),
    ]
